version: 0.0
os: linux

files:
  - source: /
    destination: /var/www
    overwrite: yes
permissions:
  - object: /var/www/
    owner: root
    group: root
hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 60
      runas: root
