name: boogObbangPlz
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make Docker Env
        run : |
          touch ./.env
          echo "{{ secrets.DOCKER_ENV }}" > ./.env
          

      - name: Make application.properties
        run: |
          mkdir -p ./backend/src/main/resources
          echo "${{ secrets.SPRING_PROPERTIES }}" > ./backend/src/main/resources/application.properties

      - name: Push Docker Image to Dockerhub
        run: |
          docker login -u ${{ secrets.DOCKER_EMAIL }} -p ${{ secrets.DOCKER_PW }}
          docker-compose build
          docker-compose push

      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USER }}
          script: |
            sh ./init_docker.sh
            docker pull ${{ secrets.DOCKER_EMAIL }}/${{ secrets.DOCKER_REPOSITORY }}-frontend
            docker-compose up -d
          
