name: boogObbangPlz
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make Docker Env
        run : |
          touch ./.env
          echo "${{ secrets.DOCKER_ENV }}" > ./.env
          

      - name: Make application.properties
        run: |
          mkdir -p ./backend/src/main/resources
          echo "${{ secrets.SPRING_PROPERTIES }}" > ./backend/src/main/resources/application.properties

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ap-northeast-2


      - name: Deliver to AWS S3
        run:
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3 }}/${{ secrets.S3 }}/$GITHUB_SHA.zip

      - name: Code Deploy To EC2
        run:
          aws deploy create-deployment 
            --application-name ${{ secrets.CODE_DEPLOY_APP_NAME }}
            --deployment-config-name CodeDeployDefault.AllAtOnce
            --deployment-group-name ${{ secrets.CODE_DEPLOY_GROUP }}
            --region ap-northeast-2
            --s3-location bucket=${{ secrets.S3 }},bundleType=zip,key=${{ secrets.S3 }}/$GITHUB_SHA.zip

          
